version: "3.9"

services:
# # ? MariaDB database service
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - docker-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

# # ? Wordpress website service
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - docker-network
    healthcheck:
      test: ["CMD-SHELL", "pidof php-fpm83 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

# ? Nginx server service
  nginx:
    container_name: nginx
    build: requirements/nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - docker-network


# # ? Volumes for persistent data
volumes:
  wordpress_db:
    driver: local
  wordpress_files:
    driver: local

# # ? Private network for inter-service communication
networks:
  docker-network:
    driver: bridge