version: "3.9"

services:
# # ? MariaDB database service
  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - docker-network

# # ? Wordpress website service
  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - mariadb
    networks:
      - docker-network

# ? Nginx server service
  nginx:
    container_name: nginx
    build: requirements/nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - wordpress
    networks:
      - docker-network


# # ? Volumes for persistent data
volumes:
  wordpress_db:
    driver: local
  wordpress_files:
    driver: local

# # ? Private network for inter-service communication
networks:
  docker-network:
    driver: bridge